/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/astryx-theme.ts
 * Command: astryx theme build lib/astryx-theme.ts
 * Generated: by scripts/theme-build.ts (timestamp normalized)
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
