/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/astryx-theme.ts
 * Command: astryx theme build lib/astryx-theme.ts
 * Generated: by scripts/theme-build.ts (timestamp normalized)
 */

/// <reference path="./speedtest.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const speedtestTheme: DefinedTheme;
